version: '3'
services:
  db:
    image: mongo:4.2
    environment:
      - MONGO_INITDB_ROOT_USERNAME: root
      - MONGO_INITDB_ROOT_PASSWORD: root
      - MONGO_INITDB_DATABASE: bowlegs
    command: --replSet rs0
    volumes:
      - ./db/data:/data/db
    networks:
      - internal
  zookeeper:
    image: wurstmeister/zookeeper
    networks:
      - internal
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092"
    environment:
      HOSTNAME_COMMAND: "route -n | awk '/UG[ \t]/{print $$2}'"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "test_topic:3:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
    networks:
      - internal
  api:
    build: ./api
    environment:
      - MONGODB_URL: 'mongodb://root:root@db:27017/bowlegs?replicaSet=rs0'
    volumes:
      - ./static:/var/content/static:ro
    networks:
      - internal
  consumer:
    build: ./consumer
    environment:

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./app/dist:/usr/share/nginx/html:ro
      - ./static:/var/content/static:ro
    networks:
      - internal
networks:
  internal: