openapi: 3.0.0
info:
  description: This is the swagger file that goes with our server code
  version: 0.1.0
  title: Swagger Computer Vision - Bow Students API

servers:
  - url: http://localhost:5000/api
    description: Development server (runs locally)
  - url: https://office.spinney.io:5623/api
    description: Production server

paths:
  /:
    get:
      operationId: api.hello
      tags:
        - Home
      summary: Says hello
      responses:
        200:
          description: OK
          content:
            text/html:
              schema:
                type: string
                example: <h1>Hello from Computer Vision - Bow Legs API</h1>
    post:
      operationId: api.predict
      tags:
        - Prediction
      summary: Returns predicted image
      requestBody:
        required: true
        content:
          image/*:
            schema:
              type: string
              format: binary
      responses:
        200:
          description: OK
          content:
            image/jpeg:
              schema:
                type: string
                format: binary
        default:
          $ref: '#/components/responses/UnexpectedError'


components:
  responses:
    UnexpectedError:
      description: Unexpected error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
  schemas:
    # Schema for error response body
    Error:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
      required:
        - code
        - message